### ISSUE TITLE
"(intermediate value)(...) is not a function" after upgrading to 1.5.1

### ISSUE THREAD

**Issue by bauer00** [heimrichhannot/contao-slick#23]
After I've upgraded to version 1.5.1 and purged the script cache the error message "(intermediate value)(...) is not a function" appears in the browser console. I've downgraded to 1.5.0 and everything works again.

I've found this change in the last version and I think this is the problem:
https://github.com/heimrichhannot/contao-slick/commit/109d5e98569d6162b9ab3f90e162f834678a1897#diff-05e0f9a851a72d62ece2611f1df09f3eR70

**Comment by fatcrobat** [comment]
Hi, are you using contao 4 or contao 3?

**Comment by bauer00** [comment]
I'm using Contao 4.4.8

**Comment by fatcrobat** [comment]
Me too, thought the workaround is no longer required, but anyways...rerolled the fix, update to 1.5.2.

**Comment by bauer00** [comment]
Yes it looks like it's still needed. Thanks for the fast update, it works perfect now.
